FROM fedora:latest

RUN dnf upgrade -y && \
	dnf install -y \
	cmake \
	ninja \
	qt6-qtbase-devel \
	qt6-qtsvg-devel \
	qt6-qtmultimedia-devel \
	gstreamer1-devel \
	gstreamer1-plugins-base-devel \
	spdlog-devel \
	taglib-devel \
	taglib-extras-devel \
	&& \
	dnf clean all

COPY ./ /openkj/
WORKDIR /openkj/
RUN cmake -DSPDLOG_USE_BUNDLED=true . -B build -G Ninja
RUN ninja -C build
